https://github.com/Getsemani-Gonzalez/getsyyv.github.io.git
echo "# getsyyv.github.io" >> README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin https://github.com/Getsemani-Gonzalez/getsyyv.github.io.git
git push -u origin master
git remote add origin https://github.com/Getsemani-Gonzalez/getsyyv.github.io.git
git push -u origin master

theme: jekyll-theme-modernist